### ISSUE TITLE
Novation Launchkey MK3 49 - controls not working

### ISSUE THREAD

**Issue by sun2sirius** [MiguelGuthridge/Universal-Controller-Script#168]
**Describe the bug**
FL Studio v21.2.1 - if I select the controller: Novation Launchkey MK3 as it comes with FL Studio, all controls work perfectly. Volume sliders control volume, tracks switch and show track names on the keyboard's display, start/stop works, etc. But notes do not play, so I was looking for alternative scripts. I installed and configured the Universal Controller Script - notes are playing, but controls do not work. In debug window it shows for volume, for example:

Not handled  Absolute 1%
Universal Controller:  B0  09  5E  Control Change: 
Not handled  Absolute -2%
Universal Controller:  B0  09  5F  Control Change: 

In Script Output window it shows "init ok", no issues.

**Comment by MaddyGuthridge** [comment]
Hello! Can you show a screenshot of your MIDI Settings? I'm guessing this might be due to the script being set up incorrectly.

**Comment by sun2sirius** [comment]
Actually, if I click on the mixer panel then sliders start working properly. However, I need sliders working while I am in the track mode - I assigned them manually, so my immediate issue was resolved and I can continue working. I was expecting to see the original script's functionality first - switching between tracks with the up/down buttons on the left side from the pads, with the track names showing on the keyboard's little display, volume sliders in track mode, etc. Maybe update documentation to explain the difference and how to get the sliders working, and that they do not work by default in track mode, and that you have to assign them manually every time in each song. IDK if what I describe is expected behavior or I am still missing some configuration/setting on my side. Thanks for your reply and looking into this!

**Comment by MaddyGuthridge** [comment]
Apologies for the late reply - I only just got a notification. This is the intended design of the script - it is supposed to "follow" you around and create logical mappings to whatever you're currently working on. You can temporarily pause this by using the [stop/solo/mute button](https://github.com/MiguelGuthridge/Universal-Controller-Script/blob/main/docs/devices/novation/launchkey.mk3.md), which stops the script from following you. If you press it on the mixer, it will keep all your controls assigned to there. I hope this helps!
